const fs = require("fs");
const path = require("path");

/** @type {import ("handlebars").HelperDelegate} */
module.exports = function (_answers, config, plop) {
  const { path: indexPath } = config;

  try {
    // re-index components
    const componentFile = path.resolve(indexPath, "index.ts");
    const components = plop.getHelper("listFiles")(indexPath, /\.component\.tsx$/);
    fs.writeFileSync(componentFile, `${plop.getPartial("autogeneratedFile")}\n`, "utf8");
    components.forEach(function (/** @type {any} */ component) {
      const componentPath = component.replace(/.*components\/(.*)\/.*/, "$1");
      fs.appendFileSync(componentFile, `export * from "./${componentPath}";\n`);
    });

    // re-index styles
    const styleFile = path.resolve(indexPath, "index.scss");
    const styles = plop.getHelper("listFiles")(indexPath, /\.styles\.scss$/);
    fs.writeFileSync(styleFile, `${plop.getPartial("autogeneratedFile")}\n`, "utf8");
    styles.forEach(function (/** @type {any} */ style) {
      const stylePath = style.replace(/.*components\/(.*)/, "$1");
      fs.appendFileSync(styleFile, `@import "./${stylePath}";\n`);
    });

    return `${indexPath}`;
  } catch (error) {
    throw `${indexPath}: ${error}`;
  }
};
