-- AlterTable
ALTER TABLE "receivables" ADD COLUMN     "settled_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "settlement_forecast_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
