const reIndexAction = require("./plop/actions/re-index");
const componentGenerator = require("./plop/generators/component");
const reIndexGenerator = require("./plop/generators/reindex");
const listDirectoriesHelper = require("./plop/helpers/list-directories");
const listFilesHelper = require("./plop/helpers/list-files");
const autogeneratedFilePartial = require("./plop/partials/autogenerated-file");

module.exports = function (/** @type {import("plop").NodePlopAPI} */ plop) {
  plop.setHelper("listDirectories", listDirectoriesHelper);
  plop.setHelper("listFiles", listFilesHelper);

  plop.setPartial("autogeneratedFile", autogeneratedFilePartial);

  plop.setActionType("reindex", reIndexAction);

  plop.setGenerator("reindex", reIndexGenerator);
  plop.setGenerator("component", componentGenerator);
};
